[palette]
[palette.light]
rosewater = "#F5E0DC"
flamingo = "#F2CDCD"
mauve = "#DDB6F2"
pink = "#F5C2E7"
maroon = "#E8A2AF"
red = "#F28FAD"
peach = "#F8BD96"
yellow = "#FAE3B0"
green = "#ABE9B3"
teal = "#B5E8E0"
blue = "#96CDFB"
sky = "#89DCEB"
lavender = "#C9CBFF"
white = "#D9E0EE"

[palette.dark]
black0 = "#161320"
black1 = "#1A1826"
black2 = "#1E1E2E"
black3 = "#302D41"
black4 = "#575268"
gray0 = "#6E6C7E"
gray1 = "#988BA2"
gray2 = "#C3BAC6"
